version: '3.0'

services:
  nginx:
    build:
      context: docker/nginx
    volumes:
      - .:/www/fb_back
      - ./docker/logs/nginx:/var/log/nginx/
    container_name: fb_nginx
#    restart: always
    ports:
      - "8882:80"
    networks:
      - skynet

  mysql:
    platform: linux/x86_64 #hack for apple m1
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: fb_mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=master"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=root"
    ports:
      - "3338:3306"
    volumes:
      - ./docker/DB:/var/lib/mysql
    networks:
      - skynet

  fb_back:
    build:
      context: docker/php-fpm
    restart: always
    container_name: fb_back
    depends_on:
      - nginx
      - mysql
    networks:
      - skynet
    volumes:
      - .:/www/fb_back

  fb_front:
    build: ../fb_front
    image: nuxt:latest
    command:
      "npm run start"
    container_name: fb_front
    tty: true
    restart: unless-stopped
    depends_on:
      - nginx
    ports:
      - "5511:5511"
    networks:
      - skynet


networks:
  skynet:
    driver: bridge
